config/routes.rb
MyEnergyUsage::Application.routes.draw do
  resources :oil_bills

  resources :electricity_bills

  resources :gas_bills

  resources :building_energy_ratings

  resources :utility_providers

  devise_for :users

  

  
  root :to => "home#index"
end

app/models/gas_bill.rb
class GasBill < ActiveRecord::Base
  track_who_does_it
end

app/controllers/gas_bills_controller.rb
class GasBillsController < ApplicationController
  before_action :set_gas_bill, only: [:show, :edit, :update, :destroy]

  # GET /gas_bills
  # GET /gas_bills.json
  def index
    @gas_bills = GasBill.all
  end

  # GET /gas_bills/1
  # GET /gas_bills/1.json
  def show
  end

  # GET /gas_bills/new
  def new
    @gas_bill = GasBill.new
  end

  # GET /gas_bills/1/edit
  def edit
  end

  # POST /gas_bills
  # POST /gas_bills.json
  def create
    @gas_bill = GasBill.new(gas_bill_params)

    respond_to do |format|
      if @gas_bill.save
        format.html { redirect_to @gas_bill, notice: 'Gas bill was successfully created.' }
        format.json { render action: 'show', status: :created, location: @gas_bill }
      else
        format.html { render action: 'new' }
        format.json { render json: @gas_bill.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /gas_bills/1
  # PATCH/PUT /gas_bills/1.json
  def update
    respond_to do |format|
      if @gas_bill.update(gas_bill_params)
        format.html { redirect_to @gas_bill, notice: 'Gas bill was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @gas_bill.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gas_bills/1
  # DELETE /gas_bills/1.json
  def destroy
    @gas_bill.destroy
    respond_to do |format|
      format.html { redirect_to gas_bills_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gas_bill
      @gas_bill = GasBill.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def gas_bill_params
      params.require(:gas_bill).permit(:start_date, :end_date, :gas_start_reading, :gas_end_reading, :net_cost, :gross_cost, :active, :users)
    end
end

app/helpers/gas_bills_helper.rb
module GasBillsHelper
end

app/views/gas_bills/_form.html.haml
= form_for @gas_bill do |f|
  - if @gas_bill.errors.any?
    #error_explanation
      %h2= "#{pluralize(@gas_bill.errors.count, "error")} prohibited this gas_bill from being saved:"
      %ul
        - @gas_bill.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :start_date
    = f.datetime_select :start_date
  .field
    = f.label :end_date
    = f.datetime_select :end_date
  .field
    = f.label :gas_start_reading
    = f.number_field :gas_start_reading
  .field
    = f.label :gas_end_reading
    = f.number_field :gas_end_reading
  .field
    = f.label :net_cost
    = f.text_field :net_cost
  .field
    = f.label :gross_cost
    = f.text_field :gross_cost
  .field
    = f.label :active
    = f.check_box :active
  .field
    = f.label :users
    = f.text_field :users
  .actions
    = f.submit 'Save'

app/views/gas_bills/edit.html.haml
%h1 Editing gas_bill

= render 'form'

= link_to 'Show', @gas_bill
\|
= link_to 'Back', gas_bills_path

app/views/gas_bills/index.html.haml
%h1 Listing gas_bills

%table
  %tr
    %th Start date
    %th End date
    %th Gas start reading
    %th Gas end reading
    %th Net cost
    %th Gross cost
    %th Active
    %th Users
    %th
    %th
    %th

  - @gas_bills.each do |gas_bill|
    %tr
      %td= gas_bill.start_date
      %td= gas_bill.end_date
      %td= gas_bill.gas_start_reading
      %td= gas_bill.gas_end_reading
      %td= gas_bill.net_cost
      %td= gas_bill.gross_cost
      %td= gas_bill.active
      %td= gas_bill.users
      %td= link_to 'Show', gas_bill
      %td= link_to 'Edit', edit_gas_bill_path(gas_bill)
      %td= link_to 'Destroy', gas_bill, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Gas bill', new_gas_bill_path

app/views/gas_bills/new.html.haml
%h1 New gas_bill

= render 'form'

= link_to 'Back', gas_bills_path

app/views/gas_bills/show.html.haml
%p#notice= notice

%p
  %b Start date:
  = @gas_bill.start_date
%p
  %b End date:
  = @gas_bill.end_date
%p
  %b Gas start reading:
  = @gas_bill.gas_start_reading
%p
  %b Gas end reading:
  = @gas_bill.gas_end_reading
%p
  %b Net cost:
  = @gas_bill.net_cost
%p
  %b Gross cost:
  = @gas_bill.gross_cost
%p
  %b Active:
  = @gas_bill.active
%p
  %b Members:
  = @gas_bill.users

= link_to 'Edit', edit_gas_bill_path(@gas_bill)
\|
= link_to 'Back', gas_bills_path