config/routes.rb
MyEnergyUsage::Application.routes.draw do
  resources :oil_bills

  resources :electricity_bills

  resources :gas_bills

  resources :building_energy_ratings

  resources :utility_providers

  devise_for :users

  

  
  root :to => "home#index"
end

app/models/oil_bill.rb
class OilBill < ActiveRecord::Base
  belongs_to :users
  track_who_does_it
end

app/controllers/oil_bills_controller.rb
class OilBillsController < ApplicationController
  before_action :set_oil_bill, only: [:show, :edit, :update, :destroy]

  # GET /oil_bills
  # GET /oil_bills.json
  def index
    @oil_bills = OilBill.all
  end

  # GET /oil_bills/1
  # GET /oil_bills/1.json
  def show
  end

  # GET /oil_bills/new
  def new
    @oil_bill = OilBill.new
  end

  # GET /oil_bills/1/edit
  def edit
  end

  # POST /oil_bills
  # POST /oil_bills.json
  def create
    @oil_bill = OilBill.new(oil_bill_params)

    respond_to do |format|
      if @oil_bill.save
        format.html { redirect_to @oil_bill, notice: 'Oil bill was successfully created.' }
        format.json { render action: 'show', status: :created, location: @oil_bill }
      else
        format.html { render action: 'new' }
        format.json { render json: @oil_bill.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /oil_bills/1
  # PATCH/PUT /oil_bills/1.json
  def update
    respond_to do |format|
      if @oil_bill.update(oil_bill_params)
        format.html { redirect_to @oil_bill, notice: 'Oil bill was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @oil_bill.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /oil_bills/1
  # DELETE /oil_bills/1.json
  def destroy
    @oil_bill.destroy
    respond_to do |format|
      format.html { redirect_to oil_bills_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_oil_bill
      @oil_bill = OilBill.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def oil_bill_params
      params.require(:oil_bill).permit(:start_date, :end_date, :volume, :net_cost, :gross_cost, :users_id)
    end
end

app/helpers/oil_bills_helper.rb
module OilBillsHelper
end

app/views/oil_bills/_form.html.haml
= form_for @oil_bill do |f|
  - if @oil_bill.errors.any?
    #error_explanation
      %h2= "#{pluralize(@oil_bill.errors.count, "error")} prohibited this oil_bill from being saved:"
      %ul
        - @oil_bill.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :start_date
    = f.datetime_select :start_date
  .field
    = f.label :end_date
    = f.datetime_select :end_date
  .field
    = f.label :volume
    = f.text_field :volume
  .field
    = f.label :net_cost
    = f.text_field :net_cost
  .field
    = f.label :gross_cost
    = f.text_field :gross_cost
  .field
    = f.label :users
    = f.text_field :users
  .actions
    = f.submit 'Save'

app/views/oil_bills/edit.html.haml
%h1 Editing oil_bill

= render 'form'

= link_to 'Show', @oil_bill
\|
= link_to 'Back', oil_bills_path

app/views/oil_bills/index.html.haml
%h1 Listing oil_bills

%table
  %tr
    %th Start date
    %th End date
    %th Volume
    %th Net cost
    %th Gross cost
    %th Members
    %th
    %th
    %th

  - @oil_bills.each do |oil_bill|
    %tr
      %td= oil_bill.start_date
      %td= oil_bill.end_date
      %td= oil_bill.volume
      %td= oil_bill.net_cost
      %td= oil_bill.gross_cost
      %td= oil_bill.users
      %td= link_to 'Show', oil_bill
      %td= link_to 'Edit', edit_oil_bill_path(oil_bill)
      %td= link_to 'Destroy', oil_bill, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Oil bill', new_oil_bill_path

app/views/oil_bills/new.html.haml
%h1 New oil_bill

= render 'form'

= link_to 'Back', oil_bills_path

app/views/oil_bills/show.html.haml
%p#notice= notice

%p
  %b Start date:
  = @oil_bill.start_date
%p
  %b End date:
  = @oil_bill.end_date
%p
  %b Volume:
  = @oil_bill.volume
%p
  %b Net cost:
  = @oil_bill.net_cost
%p
  %b Gross cost:
  = @oil_bill.gross_cost
%p
  %b Users:
  = @oil_bill.users

= link_to 'Edit', edit_oil_bill_path(@oil_bill)
\|
= link_to 'Back', oil_bills_path