config/routes.rb
MyEnergyUsage::Application.routes.draw do
  resources :oil_bills

  resources :electricity_bills

  resources :gas_bills

  resources :building_energy_ratings

  resources :utility_providers

  devise_for :users

  

  
  root :to => "home#index"
end

app/models/utility_provider.rb
class UtilityProvider < ActiveRecord::Base
  track_who_does_it
end

app/controllers/utility_providers_controller.rb
class UtilityProvidersController < ApplicationController
  before_action :set_utility_provider, only: [:show, :edit, :update, :destroy]

  # GET /utility_providers
  # GET /utility_providers.json
  def index
    @utility_providers = UtilityProvider.all
  end

  # GET /utility_providers/1
  # GET /utility_providers/1.json
  def show
  end

  # GET /utility_providers/new
  def new
    @utility_provider = UtilityProvider.new
  end

  # GET /utility_providers/1/edit
  def edit
  end

  # POST /utility_providers
  # POST /utility_providers.json
  def create
    @utility_provider = UtilityProvider.new(utility_provider_params)

    respond_to do |format|
      if @utility_provider.save
        format.html { redirect_to @utility_provider, notice: 'Utility provider was successfully created.' }
        format.json { render action: 'show', status: :created, location: @utility_provider }
      else
        format.html { render action: 'new' }
        format.json { render json: @utility_provider.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /utility_providers/1
  # PATCH/PUT /utility_providers/1.json
  def update
    respond_to do |format|
      if @utility_provider.update(utility_provider_params)
        format.html { redirect_to @utility_provider, notice: 'Utility provider was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @utility_provider.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /utility_providers/1
  # DELETE /utility_providers/1.json
  def destroy
    @utility_provider.destroy
    respond_to do |format|
      format.html { redirect_to utility_providers_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_utility_provider
      @utility_provider = UtilityProvider.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def utility_provider_params
      params.require(:utility_provider).permit(:name, :co2_coefficient, :active)
    end
end

app/helpers/utility_providers_helper.rb
module UtilityProvidersHelper
end

app/views/utility_providers/_form.html.haml
= form_for @utility_provider do |f|
  - if @utility_provider.errors.any?
    #error_explanation
      %h2= "#{pluralize(@utility_provider.errors.count, "error")} prohibited this utility_provider from being saved:"
      %ul
        - @utility_provider.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :co2_coefficient
    = f.text_field :co2_coefficient
  .field
    = f.label :active
    = f.check_box :active
  .actions
    = f.submit 'Save'

app/views/utility_providers/edit.html.haml
%h1 Editing utility_provider

= render 'form'

= link_to 'Show', @utility_provider
\|
= link_to 'Back', utility_providers_path

app/views/utility_providers/index.html.haml
%h1 Listing utility_providers

%table
  %tr
    %th Name
    %th Co2 coefficient
    %th Active
    %th
    %th
    %th

  - @utility_providers.each do |utility_provider|
    %tr
      %td= utility_provider.name
      %td= utility_provider.co2_coefficient
      %td= utility_provider.active
      %td= link_to 'Show', utility_provider
      %td= link_to 'Edit', edit_utility_provider_path(utility_provider)
      %td= link_to 'Destroy', utility_provider, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Utility provider', new_utility_provider_path

app/views/utility_providers/new.html.haml
%h1 New utility_provider

= render 'form'

= link_to 'Back', utility_providers_path

app/views/utility_providers/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @utility_provider.name
%p
  %b Co2 coefficient:
  = @utility_provider.co2_coefficient
%p
  %b Active:
  = @utility_provider.active

= link_to 'Edit', edit_utility_provider_path(@utility_provider)
\|
= link_to 'Back', utility_providers_path