config/routes.rb
MyEnergyUsage::Application.routes.draw do
  resources :oil_bills

  resources :electricity_bills

  resources :gas_bills

  resources :building_energy_ratings

  resources :utility_providers

  devise_for :users

  

  
  root :to => "home#index"
end

app/views/layouts/_messages.html.haml
-# Rails flash messages styled for Twitter Bootstrap 3.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name == :notice ? "success" : "danger"}"}
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
-# navigation styled for Twitter Bootstrap 3.0
%nav.navbar.navbar-default.navbar-fixed-top
  .container
    .navbar-header
      %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to 'Home', root_path, class: 'navbar-brand'
    .collapse.navbar-collapse
      %ul.nav.navbar-nav
        = render 'layouts/navigation_links'

app/views/layouts/_navigation_links.html.haml
- if user_signed_in?
  %li
    = link_to "My Account"
  %li
    = link_to "Oil Bills", oil_bills_path, :method => :get
  %li
    = link_to "Electricity Bills", electricity_bills_path, :method => :get
  %li
    = link_to "Gas Bills", gas_bills_path, :method => :get
  %li
    = link_to "Sign Out", destroy_user_session_path, :method => :delete
  %li
    = current_user.email
- else
  %li
    = link_to "Sign In", new_user_session_path, :method => :get
  %li
    = link_to "Sign up", new_user_registration_path, :method => :get
  

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}
    %title= content_for?(:title) ? yield(:title) : 'My Energy Usage'
    %meta{:name => "description", :content => "#{content_for?(:description) ? yield(:description) : 'My Energy Usage'}"}
    = stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
  %body
    %header
      = render 'layouts/navigation'
    %main{:role => "main"}
      = render 'layouts/messages'
      = yield